#include <biron/util/string.cpp>
#include <biron/ast_attr.cpp>
#include <biron/ast_const.cpp>
#include <biron/ast_expr.cpp>
#include <biron/ast_stmt.cpp>
#include <biron/ast_type.cpp>
#include <biron/ast_unit.cpp>
#include <biron/cg_expr.cpp>
#include <biron/cg_stmt.cpp>
#include <biron/cg_type.cpp>
#include <biron/cg_unit.cpp>
#include <biron/cg_value.cpp>
#include <biron/cg.cpp>
#include <biron/cpprt.cpp>
#include <biron/lexer.cpp>
#include <biron/llvm.cpp>
#include <biron/main.cpp>
#include <biron/parser.cpp>
#include <biron/pool.cpp>
